### ISSUE TITLE
Add Estimates to My Account/View Order page and Order Emails

### ISSUE THREAD

**Issue by decarvalhoaa** [skyverge/woocommerce-shipping-estimate#1]
I'm trying to add the shipping estimates to My Account/View Order page and Order Emails. I have came across this filter "woocommerce_order_shipping_method". This filter takes as argument a imploded array of shipment methods and I'm unsure about unexpected effects.

Do you have an idea whether it would be safe to use this filter or if there is a better filter to use for this propose?

Thanks in advance.
Cheers!

**Comment by bekarice** [comment]
Hey @decarvalhoaa, this isn't something we plan to add within this plugin. If I were doing this, I'd probably look into the `woocommerce_view_order` action for "View order" and perhaps `woocommerce_email_order_details` for orders, as you have the `$order_id` with both of these actions. This would let you get the order, loop through all shipping methods to get the estimates, and perhaps render them in your own list or table to show them in these sections.

Thanks for the feedback!
