### ISSUE TITLE
Short Code for this plugin?

### ISSUE THREAD

**Issue by hassanuos1990** [skyverge/woocommerce-shipping-estimate#11]
I need shortcode for this plugin to show estimated delivery date on any page like on checkout page. Please help.

**Comment by bekarice** [comment]
Hey @hassanuos1990 thanks for submitting this request! I'm afraid we don't have plans to add any shortcodes to the plugin, as shipping zones aren't always matched before the cart / checkout pages so estimated shipping times aren't always available this early in the process.
