### ISSUE TITLE
Fatal crash trying to upgrade to 2.2.1-dev.1

### ISSUE THREAD

**Issue by Trebacz** [skyverge/woocommerce-shipping-estimate#16]
The latest update crashes our site with a php error when we try and upgrade from version 2.2.0. The error in the php log is: Fatal error:  require_once(): Failed opening required 'blah/wp-content/plugins/woocommerce-shipping-estimate/lib/skyverge/updater/class-skyverge-plugin-license.php'

The only way to get the site back up is to rename the directory via FTP.

The file above exists with proper permissions:
-rwxr-xr-x 1 USER GROUP  21K Jul 31 19:20 class-skyverge-plugin-updater.php

I have tried deleting the plugin and reinstalling twice. Not sure what's up?

**Comment by bekarice** [comment]
@Trebacz thanks for the heads up! Sorry we missed this originally -- it looks like you were using GH updater for this plugin, and we neglected to remove support for that when we introduced an external dependency. I've removed GH updater support as a result.

You can get automated updates for the plugin [by snagging a free updater key here](https://www.skyverge.com/product/woocommerce-shipping-estimates/)
