### ISSUE TITLE
working days 

### ISSUE THREAD

**Issue by metiusat** [skyverge/woocommerce-shipping-estimate#2]
Hello,
if we set "Display estimate using dates" From days 1 to days 2

I buy something friday 22 July what do i see? Estimate delivery: 23 July to 24 July  or Estimate delivery 25 July to 26 July?

best for my case is counting working days from monday to friday.

**Comment by bekarice** [comment]
Hi @metiusat if you set delivery from 1 to 2 days, it will always be calendar days. In your scenario, a purchase on Friday July 22 would show 23 July to 24 July as the estimate. 

We don't plan to change this to business days, as this can vary from method to method (in the US, UPS doesn't deliver Saturdays, but USPS does). This would complicate the UI to set "business days" for each shipping option, as well as the logic needed to get and render these dates, so it's not something we plan to add or support in this free plugin. It would be possible if you wanted to have a developer use this plugin as a base and customize it for your needs.

Thanks for the feedback!
