### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by cristibond** [skyverge/woocommerce-shipping-estimate#23]
Hi ! 
The plugin works great! But it lacks accuracy. It should exclude non-working days.
That's all to fix.
Thanks

**Comment by bekarice** [comment]
thanks for the feedback! we don't have plans at the moment to add holiday + weekend support to the plugin so I'm going to close this, but you're welcome to use the codebase as a starting point if you'd like to expand it to add that feature -- we [recommend Codeable](https://www.skyverge.com/link/codeable-coupon) for these projects.
