### ISSUE TITLE
Issue on latest Woocommerce 5.3.0 update

### ISSUE THREAD

**Issue by Shahan-K** [skyverge/woocommerce-shipping-estimate#33]
Hi, I'm getting this message in my WordPress backend after the latest Woocommerce 5.3.0 update: 
Warning: Creating default object from empty value in /home/customer/www/rexoseal.ca/public_html/wp-content/plugins/woocommerce-shipping-estimate/lib/skyverge/updater/class-skyverge-plugin-updater.php on line 631

Message only pop-ups once in a while randomly on the backend. I noticed another user had the same error and it wasn't resolved, hope you find what the issue is.

**Comment by unfulvio** [comment]
hey @Shahan-K thanks for reporting this - we identified the problem and will release an update soon

**Comment by unfulvio** [comment]
issue should be addressed in https://github.com/skyverge/woocommerce-shipping-estimate/releases/tag/2.4.1 thanks for your patience here!
