### ISSUE TITLE
Display estimate date on single product page

### ISSUE THREAD

**Issue by kashifkiduniya** [skyverge/woocommerce-shipping-estimate#35]
Hi
Can i display shipping estimate date on single product page?

**Comment by bekarice** [comment]
hey there! we only display the estimates when the available zones + rates are determined, which happens on the cart or checkout. so, the product page is too early typically to show these estimates as we don't know where the shopper is located yet. this could be customized if you have only a couple available shipping zones or methods, but it's not something we plan to add in the plugin at this time.

We recommend using the product short description instead to show a delivery range that could apply to all shipping methods, and then letting the customer see more accurate estimates once they've been located.
