### ISSUE TITLE
great idea but sadly useless :(

### ISSUE THREAD

**Issue by webstermidia** [skyverge/woocommerce-shipping-estimate#36]
its a great idea but ends up useless due to lack of accuracy, it needs  to exclude weekends and holidays from calculations

**Comment by bekarice** [comment]
Thanks for the feedback @webstermidia ! we don't have plans at the moment to add holiday + weekend support to the plugin so I'm going to close this, but you're welcome to use the codebase as a starting point if you'd like to expand it to add that feature -- we [recommend Codeable](https://www.skyverge.com/link/codeable-coupon) for these projects.
