### ISSUE TITLE
How to use in email template?

### ISSUE THREAD

**Issue by Aalscholver** [skyverge/woocommerce-shipping-estimate#5]
Hello

Today I downloaded this plugin and so far its amazing.
I was wondering about one thing though. How can I display the estimated shipping date on emails?
For example, I use: <?php echo $order->id; ?> to get the order ID.
Is there a code like that to show the estimated shipping date?

I would love to hearing from you soon

Lucas

**Comment by bekarice** [comment]
Hey there, I don't think this is really do able without significant customization, as you don't have access to the shipping rate object in any email template filters. As a result, you'd need to completely rebuild parts of the output, so it's not something I have an example on. My best advice would be [rebuild this list of shipping method names](https://github.com/woocommerce/woocommerce/blob/663a04dfbf0d982ae18bf9aa3270cc127facb64e/includes/abstracts/abstract-wc-order.php#L767).
