### ISSUE TITLE
Is the plugin alive?

### ISSUE THREAD

**Issue by michaldybczak** [skyverge/woocommerce-shipping-estimate#7]
I see no commits for a long time and thus I'm hesitant to try it but it sounds to do exactly what I need. Without adjusting to new WP and Woocommerce, this may not work well or produce errors.

**Comment by bekarice** [comment]
Hi @michaldybczak this plugin hasn't required recent updates to work with WooCommerce. It's completely free though, so you can try it and remove it if it doesn't meet your needs 🙂

**Comment by michaldybczak** [comment]
OK, that's fair. I'll check it then. Thanks.

Usually, when a project is dead, developers are silent so there is no support and there is no development when needed so I was worried not to see recent updates.
